### ISSUE TITLE
Bug on the name of the file class WebDAVAdapter

### ISSUE THREAD

**Issue by egalantUBO** [zrisha/flysystem-webdav#1]
Hi,
When I have installed and tested this module, I found an error on the name of the class WebDAVAdapter. 
The name of this class must be WebDAVAdapter.php instead of WebDavAdapter.php.

Regards,
Eric Galant

**Comment by zrisha** [comment]
Thanks for the heads up! I made this but never actually implemented it and apparently git doesn't pick up case of files names without` git mv`.  Should be fixed in eb76c88ac79112ef4b893708e889acd01cc1dfe0.
